#To deploy on your local machine for testing purposes
version: "3"

services:
  react-component:
    build:
      context: ./
      dockerfile: ./deployment/depl_ui/Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://rust-api:5000/notes

  rust-api:
    build:
      context: ./
      dockerfile: ./deployment/depl_server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/server
      HOST: 0.0.0.0
      PORT: 5000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: server
    volumes:
      - /pgdata:/var/lib/postgresql/data
      - ./deployment/depl_db/postgresql.conf:/etc/postgresql.conf
    ports:
      - "5432:5432"
